puts "Removing #{Brewery.count} breweries"
Brewery.delete_all

# Current as of 2013-11-11
breweries = [
  ["http://www.acousticales.com/", "Acoustic Ales Brewing Experiment", "Midtown", 2013],
  ["http://alesmith.com/", "AleSmith Brewing Company", "Miramar", nil],
  ["http://www.alpinebeerco.com/", "Alpine Beer Company", "Alpine", nil],
  ["http://www.amplifiedales.com/", "Amplified Ale Works", "Pacific Beach", 2012],
  ["http://www.arcanabrewing.com/", "Arcana Brewing Co.", "Carlsbad", nil],
  ["http://automaticbrewingco.com/", "Automatic Brewing Company", "Normal Heights", nil],
  ["http://www.aztecbrewery.com/home.html", "Aztec Brewing Company / 7 Nations Brewing Company", "Vista", nil],
  ["http://www.lamppostpizza.com/backstreet/", "Back Street Brewery", "Vista", nil],
  ["http://www.ballastpoint.com/", "Ballast Point Brewing & Spirits", "Scripps Ranch", nil],
  ["http://www.ballastpoint.com/", "Ballast Point Home Brew Mart", "Linda Vista", nil],
  ["http://www.ballastpoint.com/", "Ballast Point Little Italy", "Little Italy", 2013],
  ["http://www.barrelharborbrewing.com/", "Barrel Harbor", "Vista", 2013],
  ["https://www.facebook.com/pages/The-Belching-Beaver/157351577682127", "Belching Beaver Brew", "Vista", 2012],
  ["http://www.benchmarkbrewing.com/", "Benchmark Brewing", "Grantville", 2013],
  ["http://www.bnsbrewinganddistilling.com/", "BNS Brewing & Distilling", "Santee", 2013],
  ["http://boozebrothersbrewery.com/", "Booze Brothers", "Vista", 2013],
  ["http://breakwaterbrewing.com/", "Breakwater Brewing Company", "Oceanside", nil],
  ["http://butchersbrewing.com/", "Butcher’s Brewing", "Santee", 2013],
  ["http://www.chuckalek.com/", "ChuckAlek Independent Brewers", "Ramona", 2013],
  ["http://coldborebrewing.com/index.html", "Cold Bore Brewing Company", "Jamul", nil],
  ["http://coronadobrewingcompany.com/", "Coronado Brewing Company", "Coronado", nil],
  ["http://coronadobrewingcompany.com/", "Coronado Brewing Company", "Bay Park", 2013],
  ["http://www.facebook.com/CultureBrewingCo?fref=ts", "Culture Brewing Co.", "Solana Beach", 2013],
  ["http://www.fallbrookbrewing.com/", "Fallbrook Brewing Company", "Fallbrook", 2013],
  ["http://www.gordonbiersch.com/", "Gordon Biersch Brewery Restaurant", "Mission Valley", nil],
  ["http://www.greenflashbrew.com/", "Green Flash Brewing Co.", "Mira Mesa", nil],
  ["http://groundswellbrew.com/", "Groundswell Brewing Co.", "Grantville", 2013],
  ["http://helmsbrewingco.com/", "Helm’s Brewing", "Kearny Mesa", 2012],
  ["http://hessbrewing.com/", "Hess Brewing", "Miramar", nil],
  ["http://hessbrewing.com/", "Hess Brewing", "North Park", 2013],
  ["http://hillcrestbrewingcompany.com/", "Hillcrest Brewing Company", "Hillcrest", 2012],
  ["http://indianjoebeer.com/", "Indian Joe Beer", "Vista", 2012],
  ["http://intergalacticbrew.com/beer.html", "Intergalactic Brewing Co.", "Mira Mesa", 2013],
  ["http://www.ironfistbrewing.com/", "Iron Fist Brewing Company", "Vista", nil],
  ["http://www.facebook.com/julianbrewing", "Julian Brewing Company", "Julian", 2012],
  ["http://www.karlstrauss.com/PAGES/Eats/4SRanch.html", "Karl Strauss 4s Ranch", "4S Ranch", 2012],
  ["http://www.karlstrauss.com/", "Karl Strauss Carlsbad", "Carlsbad", nil],
  ["http://www.karlstrauss.com/", "Karl Strauss Downtown", "Downtown", nil],
  ["http://www.karlstrauss.com/", "Karl Strauss La Jolla", "La Jolla", nil],
  ["http://www.karlstrauss.com/", "Karl Strauss Main Production Brewery", "Pacific Beach", nil],
  ["http://www.karlstrauss.com/", "Karl Strauss Sorrento Mesa", "Sorrento Mesa", nil],
  ["http://knbwinecellars.com/ ", "KnB Cellars", "Del Cerro", 2013],
  ["http://www.lat33brew.com/", "Latitude 33 Brewing Company", "Vista", 2012],
  ["https://www.facebook.com/LegacyBrewingCompany", "Legacy Brewing", "Oceanside", 2013],
  ["http://www.lightningbrewery.com/", "Lightning Brewery", "Poway", nil],
  ["http://www.manzanitabrewing.com/", "Manzanita Brewing Company", "Santee", nil],
  ["http://missionbrewery.com/", "Mission Brewery", "Downtown", nil],
  ["http://moderntimesbeer.com/", "Modern Times", "Midway", 2013],
  ["http://monkeypawbrewing.com/", "Monkey Paw Pub & Brewery", "East Village", nil],
  ["http://www.motherearthbrewco.com/", "Mother Earth Brew Company", "Vista", nil],
  ["http://www.newenglishbrewing.com/", "New English Brewing Company", "Sorrento Valley", nil],
  ["http://www.oceansidealeworks.net/", "Oceanside Ale Works", "Oceanside", nil],
  ["http://www.offbeatbrewing.com", "Offbeat Brewing Company", "Escondido", 2012],
  ["http://www.oggis.com/", "Oggi’s Pizza & Brewing Company Fenton Parkway", "Mission Valley", nil],
  ["http://www.ottbrew.com/", "On-The-Tracks Brewery", "Carlsbad", nil],
  ["http://www.pbalehouse.com/", "Pacific Beach Ale House", "Pacific Beach", nil],
  ["http://www.pizzaport.com/locations/pizza-port-bressi-ranch/", "Pizza Port Bressi Ranch", "Bressi Ranch", 2013],
  ["http://www.pizzaport.com/Pizza-Port-Carlsbad-s/1818.htm", "Pizza Port Carlsbad", "Carlsbad", nil],
  ["http://www.pizzaport.com/category-s/1819.htm", "Pizza Port Ocean Beach", "Ocean Beach", nil],
  ["http://www.pizzaport.com/category-s/1820.htm", "Pizza Port Solana Beach", "Solana Beach", nil],
  ["http://www.facebook.com/pages/Plan-9-Alehouse/181129215255385?ref=ts", "Plan 9 Ale House", "Escondido", 2013],
  ["http://www.poorhousebrew.com/", "Poor House Brewing Co", "North Park", 2012],
  ["http://www.lostabbey.com/", "Port Brewing / The Lost Abbey", "San Marcos", nil],
  ["http://prohibitionbrewingcompany.com/", "Prohibition Brewing Company", "Vista", nil],
  ["http://www.beerpulse.com/2012/03/2011-national-homebrewing-conference-champion-to-start-new-brewery-in-california/", "Rip Current Brewing Co.", "San Marcos", 2012],
  ["http://www.rockbottom.com/la-jolla", "Rock Bottom Brewery Restaurant La Jolla", "La Jolla", nil],
  ["http://www.roughdraftbrew.com/", "Rough Draft Brewing Company", "Mira Mesa", 2012],
  ["http://www.sandiegobrewing.com/", "San Diego Brewing Company", "Grantville", nil],
  ["http://sanmarcosbrewery.com/", "San Marcos Brewery & Grill", "San Marcos", nil],
  ["http://www.societebrewing.com/", "Societe Brewing Co.", "Kearny Mesa", 2012],
  ["http://saintarcherbrewery.com/", "St. Archer Brewing Co.", "Miramar", 2013],
  ["http://www.stonebrew.com/ ", "Stone Brewing Company", "Escondido", nil],
  ["http://www.stonebrew.com/news/110523pr/ls/", "Stone Liberty Station", "Liberty Station", 2013],
  ["http://www.stumblefoot.com/", "Stumblefoot Brewing Company", "San Marcos", 2012],
  ["http://thebeerco.net/", "The Beer Company", "Downtown", nil],
  ["http://www.westcoastersd.com/2012/02/06/home-brews-gardens-loses-key-employees-the-homebrewer-opening-soon-all-about-brewing-grows/", "Thorn St. Brewery", "North Park", 2012],
  ["http://twokidsbrewing.blogspot.com/", "Two Kids Brewing Co.", "Mira Mesa", 2013],
  ["http://www.valleycenterbrewery.com/", "Valley Center Brewing", "Valley Center", 2013],
  ["http://www.wetnreckless.com/", "Wet ‘N Reckless Brewing Company", "Mira Mesa", 2012],
  ["http://whitelabs.com/", "White Labs experimental beer tasting room", "Miramar", 2012]
]

breweries.each do |brewery|
  raise ArgumentError unless brewery.length == 4
  url, name, location, year = *brewery
  Brewery.create! name: name, url: url, location: location, year_opened: year
end

puts "Added #{Brewery.count} breweries"
